// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:unyo/core/enums/episode_service.dart';
import 'package:unyo/core/enums/service.dart';
import 'package:unyo/data/models/anilist_anime_details.dart';
import 'package:unyo/data/models/anilist_manga_details.dart';
import 'package:unyo/data/models/anilist_user_model.dart';
import 'package:unyo/data/models/local_user_model.dart';
import 'package:unyo/domain/entities/extension.dart';
import 'package:unyo/domain/entities/media_list.dart';
import 'package:unyo/domain/entities/media_list_entry.dart';
import 'package:unyo/domain/entities/settings.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AnilistUserModelAdapter());
    registerAdapter(AnimeProgressModelAdapter());
    registerAdapter(EpisodeServiceEnumAdapter());
    registerAdapter(ExtensionModelAdapter());
    registerAdapter(LocalUserModelAdapter());
    registerAdapter(MangaProgressModelAdapter());
    registerAdapter(MediaListEntryModelAdapter());
    registerAdapter(MediaListModelAdapter());
    registerAdapter(ServiceEnumAdapter());
    registerAdapter(SettingsModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AnilistUserModelAdapter());
    registerAdapter(AnimeProgressModelAdapter());
    registerAdapter(EpisodeServiceEnumAdapter());
    registerAdapter(ExtensionModelAdapter());
    registerAdapter(LocalUserModelAdapter());
    registerAdapter(MangaProgressModelAdapter());
    registerAdapter(MediaListEntryModelAdapter());
    registerAdapter(MediaListModelAdapter());
    registerAdapter(ServiceEnumAdapter());
    registerAdapter(SettingsModelAdapter());
  }
}
